//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.08 at 09:32:35 AM AEST 
//


package com.kuai.traffic.simulator.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.simulator.traffic.kuai.com/model}position" maxOccurs="2" minOccurs="2"/>
 *         &lt;element ref="{http://www.simulator.traffic.kuai.com/model}road" maxOccurs="3" minOccurs="2"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="road1Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="road2Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="road3Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="road4Id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "position",
    "road"
})
@XmlRootElement(name = "intersection")
public class Intersection {

    @XmlElement(required = true)
    protected List<Position> position;
    @XmlElement(required = true)
    protected List<Road> road;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "road1Id")
    protected String road1Id;
    @XmlAttribute(name = "road2Id")
    protected String road2Id;
    @XmlAttribute(name = "road3Id")
    protected String road3Id;
    @XmlAttribute(name = "road4Id")
    protected String road4Id;

    /**
     * Gets the value of the position property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the position property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Position }
     * 
     * 
     */
    public List<Position> getPosition() {
        if (position == null) {
            position = new ArrayList<Position>();
        }
        return this.position;
    }

    /**
     * Gets the value of the road property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the road property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Road }
     * 
     * 
     */
    public List<Road> getRoad() {
        if (road == null) {
            road = new ArrayList<Road>();
        }
        return this.road;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the road1Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoad1Id() {
        return road1Id;
    }

    /**
     * Sets the value of the road1Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoad1Id(String value) {
        this.road1Id = value;
    }

    /**
     * Gets the value of the road2Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoad2Id() {
        return road2Id;
    }

    /**
     * Sets the value of the road2Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoad2Id(String value) {
        this.road2Id = value;
    }

    /**
     * Gets the value of the road3Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoad3Id() {
        return road3Id;
    }

    /**
     * Sets the value of the road3Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoad3Id(String value) {
        this.road3Id = value;
    }

    /**
     * Gets the value of the road4Id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoad4Id() {
        return road4Id;
    }

    /**
     * Sets the value of the road4Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoad4Id(String value) {
        this.road4Id = value;
    }

}
